export type AccessComponentSourceRow = {
  DBID: string;
  WP_GUID: string;
  ACTIVITYGROUP: string;
  TITLE: string;
  RESULT: string;
  PHOTO_TAKEN: string;
  SIGNEE: string;
  TIMESTAMP: string;
  TEMPLATE: string;
  PROJECT_NAME: string;
};

export const componentSource: AccessComponentSourceRow[] = [
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Framing",
    TITLE: "Slings Installed",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Section Sign Off",
    TITLE: "Framing Sign Off",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Section Sign Off",
    TITLE: "Lining Inside Sign Off",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Framing",
    TITLE: "Fixings as per drawings",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Outside 2",
    TITLE: "Product and layout as per Shop Drawings",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Outside 1",
    TITLE: "Airtightness Strip Installed",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Outside 1",
    TITLE: "Fixings",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Outside 1",
    TITLE: "Product and layout as per Shop Drawings",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Services",
    TITLE: "Fire rated panel, use fire rated flush boxes",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Outside 2",
    TITLE: "Fixing Treatment",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Inside 2",
    TITLE: "Product and layout as per Shop Drawings",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Inside 2",
    TITLE: "Fixing Treatment",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Inside 1",
    TITLE: "Fixings",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Lining Inside 1",
    TITLE: "Fixing Treatment",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Quality Check",
    TITLE: "Final Sign off by QC person",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Services",
    TITLE: "Take photos of fire rated boxes, conduit runs, taping",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
  {
    DBID: "738",
    WP_GUID: "42_IW_0006",
    ACTIVITYGROUP: "Framing",
    TITLE: "Squared",
    RESULT: "",
    PHOTO_TAKEN: "",
    SIGNEE: "",
    TIMESTAMP: "",
    TEMPLATE: "EW_I1E1",
    PROJECT_NAME: "Schubert residence",
  },
];