import { db } from './db';
import type { Project, Panel } from './types';

const uuid = () => crypto.randomUUID();

const componentSource: Array<{ group: string; panel: string; template: string }> = [
  { group: 'MF_1', panel: 'Bal_001', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_002', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_003', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_004', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_005', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_006', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_007', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_008', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_009', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_010', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_011', template: 'EW_I1E1' },
  { group: 'MF_1', panel: 'Bal_012', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0001', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0002', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0003', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0004', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0005', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0006', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0007', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0008', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0009', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0010', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0011', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0012', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0013', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0014', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0015', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0016', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0017', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0018', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0019', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0020', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0021', template: 'EW_I1E1' },
  { group: 'EW_0', panel: 'EW_0022', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1001', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1002', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1003', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1004', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1005', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1006', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1007', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1008', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1009', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1010', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1011', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1012', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1013', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1014', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1015', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1016', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1017', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1018', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1019', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1020', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1021', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1022', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1023', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1024', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1025', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1026', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1027', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1028', template: 'EW_I1E1' },
  { group: 'EW_1', panel: 'EW_1029', template: 'EW_I1E1' },
  { group: 'Roof', panel: 'EW_2001', template: 'EW_I1E1' },
  { group: 'Roof', panel: 'EW_2002', template: 'EW_I1E1' },
  { group: 'Roof', panel: 'EW_2003', template: 'EW_I1E1' },
  { group: 'Roof', panel: 'EW_2004', template: 'EW_I1E1' },
  { group: 'IW_0', panel: 'IW_0001', template: 'IW_I1E1' },
  { group: 'IW_0', panel: 'IW_0002', template: 'IW_I1E1' },
  { group: 'IW_0', panel: 'IW_0003', template: 'IW_I1E1' },
  { group: 'IW_0', panel: 'IW_0004', template: 'IW_I1E1' },
  { group: 'IW_0', panel: 'IW_0005', template: 'IW_I1E1' },
  { group: 'IW_0', panel: 'IW_0006', template: 'IW_I1E1' },
  { group: 'IW_0', panel: 'IW_0007', template: 'IW_I1E1' },
  { group: 'IW_0', panel: 'IW_0008', template: 'IW_I1E1' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0020', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0021', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0022', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0023', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0024', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0025', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0026', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0027', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0028', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0029', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0030', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0031', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0032', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0033', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0034', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0035', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_0037', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0040', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0041', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0042', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0043', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0044', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0045', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0046', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0047', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0048', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0049', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0050', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0051', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0052', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0053', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0054', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0055', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_0057', template: 'IW_I0E0' },
  { group: 'IW_1', panel: 'IW_1001', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1002', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1003', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1004', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1005', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1006', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1007', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1008', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1009', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1010', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1011', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1012', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1013', template: 'IW_I1E1' },
  { group: 'IW_1', panel: 'IW_1014', template: 'IW_I1E1' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1020', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1021', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1022', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1023', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1024', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1025', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1026', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1027', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1028', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1029', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1030', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1031', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1032', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1033', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1034', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1035', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1036', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_1038', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1040', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1041', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1042', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1043', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1044', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1045', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1046', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1047', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1048', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1049', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1050', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1051', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1052', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1053', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1054', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1055', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1056', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_1058', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_BulkHd_A', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_BulkHd_A', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-05)', panel: 'IW_BulkHd_B', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-06)', panel: 'IW_BulkHd_B', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_BulkHd_C', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_BulkHd_C', template: 'IW_I0E0' },
  { group: 'IW_0_(unit-07)', panel: 'IW_BulkHd_D', template: 'IW_I0E0' },
  { group: 'IW_1_(unit-08)', panel: 'IW_BulkHd_D', template: 'IW_I0E0' },
  { group: 'MF_1', panel: 'MF_0001', template: 'MF_T1B0' },
  { group: 'MF_1', panel: 'MF_0002', template: 'MF_T1B0' },
  { group: 'MF_1', panel: 'MF_0003', template: 'MF_T1B0' },
  { group: 'MF_1', panel: 'MF_0004', template: 'MF_T1B0' },
  { group: 'EW_1', panel: 'MF_1001', template: 'MF_T1B0' },
  { group: 'EW_1', panel: 'MF_1002', template: 'MF_T1B0' },
  { group: 'EW_1', panel: 'MF_1003', template: 'MF_T1B0' },
  { group: 'EW_1', panel: 'MF_1004', template: 'MF_T1B0' },
  { group: 'EW_1', panel: 'MF_1005', template: 'MF_T1B0' },
  { group: 'Roof', panel: 'R_0001', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0002', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0003', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0004', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0005', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0006', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0007', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0008', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0009', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0010', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0011', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0012', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0013', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0014', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0015', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0016', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0017', template: 'RO_I1E1_BI' },
  { group: 'Roof', panel: 'R_0018', template: 'RO_I1E1_BI' },
  { group: 'Structure', panel: 'RB_01', template: 'STR_1' },
  { group: 'Structure', panel: 'RB_02', template: 'STR_1' },
  { group: 'Structure', panel: 'RB_03', template: 'STR_1' },
  { group: 'Structure', panel: 'RB_04', template: 'STR_1' },
  { group: 'Structure', panel: 'RB_05', template: 'STR_1' },
  { group: 'Structure', panel: 'RB_06', template: 'STR_1' },
  { group: 'Stair_0', panel: 'ST_001', template: 'RO_I1E1_BI' },
  { group: 'Stair_STRU', panel: 'ST_001_STRU', template: 'STR_1' },
  { group: 'Stair_0', panel: 'ST_002', template: 'RO_I1E1_BI' },
  { group: 'Stair_STRU', panel: 'ST_002_STRU', template: 'RO_I1E1_BI' },
  { group: 'Roof_STRU', panel: 'STRU_R01', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R02', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R03', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R04', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R05', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R06', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R07', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R08', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R10', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R11', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R12', template: 'STR_1' },
  { group: 'Roof_STRU', panel: 'STRU_R13', template: 'STR_1' },
  { group: 'PC', panel: 'PRECUT_01', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_02', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_03', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_04', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_05', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_06', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_07', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_08', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_09', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_10', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_11', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_12', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_13', template: 'PC_1' },
  { group: 'PC', panel: 'PRECUT_14', template: 'PC_1' },
  { group: 'LP', panel: 'LP_01', template: 'LP_1' },
  { group: 'LP', panel: 'LP_02', template: 'LP_1' },
  { group: 'LP', panel: 'LP_03', template: 'LP_1' },
  { group: 'LP', panel: 'LP_04', template: 'LP_1' },
  { group: 'LP', panel: 'LP_05', template: 'LP_1' },
  { group: 'LP', panel: 'LP_06', template: 'LP_1' },
  { group: 'LP', panel: 'LP_07', template: 'LP_1' },
  { group: 'LP', panel: 'LP_08', template: 'LP_1' },
  { group: 'LP', panel: 'LP_09', template: 'LP_1' },
];

const inferTypeFromGroup = (group: string): Panel['type'] => {
  const normalized = group.toLowerCase();
  if (normalized.startsWith('ew')) return 'ew';
  if (normalized.startsWith('iw')) return 'iw';
  if (normalized.startsWith('mf')) return 'mf';
  if (normalized.startsWith('roof') || normalized === 'roof' || normalized.startsWith('r_')) {
    return 'r';
  }
  return 'sw';
};

export async function seedIfEmpty() {
  await db.transaction('rw', db.projects, db.components, async () => {
    const projects = await db.projects.toArray();
    let project = projects[0];

    if (!project) {
      project = {
        project_id: uuid(),
        project_code: '230041',
        project_name: 'Alpine Residences Jacks Point — Alpine Block 4B (PS114)',
        status: 'active',
      } satisfies Project;
      await db.projects.add(project);
    } else if (projects.length > 1) {
      const duplicates = projects.slice(1).map((item) => item.project_id);
      if (duplicates.length) {
        await db.projects.bulkDelete(duplicates);
      }
    }

    if (!project) {
      return;
    }

    const componentCount = await db.components
      .where({ project_id: project.project_id })
      .count();

    if (componentCount === 0) {
      const components: Panel[] = componentSource.map(({ group, panel, template }) => ({
        project_id: project!.project_id,
        type: inferTypeFromGroup(group),
        group: group,
        panel_id: panel,
        template_id: template,
      }));

      await db.components.bulkAdd(components);
    }
  });
}
